version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
